### ISSUE TITLE
Sida med närliggande restauranger

### ISSUE THREAD

**Issue by Jassob** [dtekcth/DtekPortalenRemake#13]
Mat.dtek.se
===========

Vi borde ha en mat.dtek.se som visar exempelvis alpa och pizzerior osv.

**Radio** vill se en snyggare och konkurrenskraftig motståndare till http://pizza.chalmers.it, med sökmotor för sannegården så klart.

Se [Pizzor med kebab](http://pizza.chalmers.it/pizza/?q=kebab)

**Comment by profil** [comment]
@adamse har byggt en göddig matsida för kårresturangen, einstein och linsen som jag använder dagligen.

**Comment by adamse** [comment]
http://mat.hatarkul.se/

**Comment by Jassob** [comment]
Jo, den sidan är klockren för kårens mat och Einstein, men jag tänker mer på typ pizzerior och miss fajitas och sushiställen. 

Någon enklare form av informationssida med öppettider och gärna menyer liksom

**Comment by adamse** [comment]
http://www.drygast.nu/
