### ISSUE TITLE
Nav-system

### ISSUE THREAD

**Issue by cpluss** [dtekcth/DtekPortalenRemake#15]
Navigations-system
=============================

Enkelt navigationssystem, för tillfället statiskt i någon dictionary/array. Blir för mycket arbete med att hålla helt i databas med tanke på dynamiska bindningar till sidor i admin-interface vid senare skede.

**Comment by cpluss** [comment]
Done (ja, jag pushar direkt till master, mwuhahah)

**Comment by Jassob** [comment]
Snajsigt, ska bli kul att sätta sig in i kombon Sinatra + React snart!

//Jassob
