### ISSUE TITLE
Föreningsprofiler

### ISSUE THREAD

**Issue by cpluss** [dtekcth/DtekPortalenRemake#19]
Dynamiska föreningsprofiler

**Comment by Jassob** [comment]
# Kort information
Börja med dynamiska sidmodeller i Sinatra/Ruby.
Ska innehålla: pageid, title, name, content.

Varje föreningssida visar upp information om en förening.
Tanken är att adminvyn ska innehålla en textredigerare där man kan mata in Markdown som sedan renderas som HTML på föreningssidan.

Bilder osv kan komma senare.
